package = {
    name = "musl",
    version = "1.2.6",
    hash = "d585fd3b613c66151fc3249e8ed44f77020cb5e6c1e635a616d3f9f82460512a",
    source = "https://musl.libc.org/releases/musl-1.2.6.tar.gz",
    architecture = "x86_64",
    branch = "cross",
    build_style = "gnu-configure",

    configure_flags = {
        "--prefix=/usr",
        "--target=x86_64-aqua-linux-musl",
	"--syslibdir=/usr/lib"
    }
}
